homepage:
    pattern:  /
    defaults: { _controller: SFMFormsBundle:Main:new }

sfm_forms:
    resource: "@SFMFormsBundle/Resources/config/routing.yml"
    prefix: /

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
